name: build

on:
  push:

env:
  python-version: '3.12'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ env.python-version }}
          allow-prereleases: true
      - name: Install PDM
        run: python${{ env.python-version }} -m pip install pdm
      - name: Install dependencies
        run: python${{ env.python-version }} -m pdm install
      - name: Test
        run: python${{ env.python-version }} -m pdm run pytest
